/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CancelButton: typeof import('./src/components/cancel-button.vue')['default']
    Cell: typeof import('./src/components/cell.vue')['default']
    CellGroup: typeof import('./src/components/cell-group.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    DelButton: typeof import('./src/components/del-button.vue')['default']
    Field: typeof import('./src/components/field.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    PrimaryButton: typeof import('./src/components/primary-button.vue')['default']
    Progress: typeof import('./src/components/progress.vue')['default']
    StatusIcon: typeof import('./src/components/status-icon.vue')['default']
    TimePickerField: typeof import('./src/components/time-picker-field.vue')['default']
    TimeProgress: typeof import('./src/components/time-progress.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNotify: typeof import('vant/es')['Notify']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}
